apiVersion: 1

datasources:
  - name: Prometheus
    uid: cfmh94yfqwjcwd
    type: prometheus
    access: proxy
    url: http://devops-prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      httpMethod: POST
