apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-provisioning-datasources
  namespace: devops
data:
  prometheus.yml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        uid: cfmh94yfqwjcwd
        type: prometheus
        access: proxy
        url: http://devops-prometheus:9090
        isDefault: true
        editable: true
        jsonData:
          httpMethod: POST
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-provisioning-dashboards
  namespace: devops
data:
  devops.yml: |
    apiVersion: 1
    providers:
      - name: DevOps Control Center
        orgId: 1
        folder: ""
        type: file
        disableDeletion: false
        updateIntervalSeconds: 10
        allowUiUpdates: true
        options:
          path: /etc/grafana/dashboards
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboards
  namespace: devops
data:
  node-exporter-full.json: |
    {
      "annotations": {
        "list": [
          {
            "builtIn": 1,
            "datasource": {
              "type": "grafana",
              "uid": "-- Grafana --"
            },
            "enable": true,
            "hide": true,
            "iconColor": "rgba(0, 211, 255, 1)",
            "name": "Annotations & Alerts",
            "type": "dashboard"
          }
        ]
      },
      "editable": true,
      "fiscalYearStartMonth": 0,
      "graphTooltip": 0,
      "id": null,
      "links": [],
      "liveNow": false,
      "panels": [
        {
          "datasource": {
            "type": "prometheus",
            "uid": "${ds_prometheus}"
          },
          "fieldConfig": {
            "defaults": {
              "color": {
                "mode": "palette-classic"
              },
              "decimals": 1,
              "max": 100,
              "min": 0,
              "thresholds": {
                "mode": "absolute",
                "steps": [
                  {
                    "color": "green",
                    "value": null
                  },
                  {
                    "color": "yellow",
                    "value": 70
                  },
                  {
                    "color": "red",
                    "value": 90
                  }
                ]
              },
              "unit": "percent"
            },
            "overrides": []
          },
          "gridPos": {
            "h": 8,
            "w": 12,
            "x": 0,
            "y": 0
          },
          "id": 77,
          "options": {
            "legend": {
              "calcs": [
                "lastNotNull"
              ],
              "displayMode": "list",
              "placement": "bottom",
              "showLegend": true
            },
            "tooltip": {
              "mode": "single",
              "sort": "none"
            }
          },
          "targets": [
            {
              "datasource": {
                "type": "prometheus",
                "uid": "${ds_prometheus}"
              },
              "editorMode": "code",
              "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{job=\"$job\", instance=\"$node\", mode=\"idle\"}[$__rate_interval])) * 100)",
              "legendFormat": "CPU usage",
              "range": true,
              "refId": "A"
            }
          ],
          "title": "CPU Usage",
          "type": "timeseries"
        },
        {
          "datasource": {
            "type": "prometheus",
            "uid": "${ds_prometheus}"
          },
          "fieldConfig": {
            "defaults": {
              "color": {
                "mode": "palette-classic"
              },
              "decimals": 1,
              "max": 100,
              "min": 0,
              "thresholds": {
                "mode": "absolute",
                "steps": [
                  {
                    "color": "green",
                    "value": null
                  },
                  {
                    "color": "yellow",
                    "value": 70
                  },
                  {
                    "color": "red",
                    "value": 90
                  }
                ]
              },
              "unit": "percent"
            },
            "overrides": []
          },
          "gridPos": {
            "h": 8,
            "w": 12,
            "x": 12,
            "y": 0
          },
          "id": 78,
          "options": {
            "legend": {
              "calcs": [
                "lastNotNull"
              ],
              "displayMode": "list",
              "placement": "bottom",
              "showLegend": true
            },
            "tooltip": {
              "mode": "single",
              "sort": "none"
            }
          },
          "targets": [
            {
              "datasource": {
                "type": "prometheus",
                "uid": "${ds_prometheus}"
              },
              "editorMode": "code",
              "expr": "(1 - (node_memory_MemAvailable_bytes{job=\"$job\", instance=\"$node\"} / node_memory_MemTotal_bytes{job=\"$job\", instance=\"$node\"})) * 100",
              "legendFormat": "Memory usage",
              "range": true,
              "refId": "A"
            }
          ],
          "title": "Memory Usage",
          "type": "timeseries"
        }
      ],
      "refresh": "5s",
      "schemaVersion": 41,
      "style": "dark",
      "tags": [
        "devops-control-center",
        "node-exporter"
      ],
      "templating": {
        "list": [
          {
            "current": {
              "selected": false,
              "text": "Prometheus",
              "value": "cfmh94yfqwjcwd"
            },
            "hide": 2,
            "label": "Prometheus",
            "name": "ds_prometheus",
            "query": "prometheus",
            "refresh": 1,
            "type": "datasource"
          },
          {
            "current": {
              "selected": false,
              "text": "node",
              "value": "node"
            },
            "hide": 2,
            "label": "Job",
            "name": "job",
            "query": "node",
            "type": "constant"
          },
          {
            "current": {
              "selected": false,
              "text": "node-exporter:9100",
              "value": "node-exporter:9100"
            },
            "hide": 2,
            "label": "Node",
            "name": "node",
            "query": "node-exporter:9100",
            "type": "constant"
          },
          {
            "current": {
              "selected": false,
              "text": "node-exporter",
              "value": "node-exporter"
            },
            "hide": 2,
            "label": "Node name",
            "name": "nodename",
            "query": "node-exporter",
            "type": "constant"
          }
        ]
      },
      "time": {
        "from": "now-15m",
        "to": "now"
      },
      "timepicker": {},
      "timezone": "browser",
      "title": "Node Exporter Full",
      "uid": "rYdddlPWk",
      "version": 1,
      "weekStart": ""
    }
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-data-pvc
  namespace: devops
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-grafana
  namespace: devops
  labels:
    app: devops-grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-grafana
  template:
    metadata:
      labels:
        app: devops-grafana
    spec:
      securityContext:
        fsGroup: 472
      containers:
      - name: grafana
        image: grafana/grafana:latest
        ports:
        - containerPort: 3000
        env:
        - name: GF_SECURITY_ALLOW_EMBEDDING
          value: "true"
        - name: GF_AUTH_ANONYMOUS_ENABLED
          value: "true"
        - name: GF_AUTH_ANONYMOUS_ORG_ROLE
          value: "Admin"
        - name: GF_SERVER_DOMAIN
          value: "devops.mattdev0.tech"
        - name: GF_SERVER_ROOT_URL
          value: "https://devops.mattdev0.tech/grafana/"
        - name: GF_SERVER_SERVE_FROM_SUB_PATH
          value: "true"
        - name: GF_SECURITY_COOKIE_SAMESITE
          value: "lax"
        - name: GF_SECURITY_COOKIE_SECURE
          value: "true"
        - name: GF_SERVER_ENFORCE_DOMAIN
          value: "false"
        resources:
          requests:
            memory: "128Mi"
            cpu: "20m"
          limits:
            memory: "512Mi"
            cpu: "200m"
        volumeMounts:
        - name: grafana-storage
          mountPath: /var/lib/grafana
        - name: prov-datasources
          mountPath: /etc/grafana/provisioning/datasources
        - name: prov-dashboards
          mountPath: /etc/grafana/provisioning/dashboards
        - name: dashboards
          mountPath: /etc/grafana/dashboards
      volumes:
      - name: grafana-storage
        persistentVolumeClaim:
          claimName: grafana-data-pvc
      - name: prov-datasources
        configMap:
          name: grafana-provisioning-datasources
      - name: prov-dashboards
        configMap:
          name: grafana-provisioning-dashboards
      - name: dashboards
        configMap:
          name: grafana-dashboards
---
apiVersion: v1
kind: Service
metadata:
  name: devops-grafana
  namespace: devops
spec:
  type: NodePort
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30010
    protocol: TCP
  selector:
    app: devops-grafana
